# Generated by Django 5.0 on 2024-10-16 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ASTNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('operator', 'Operator'), ('operand', 'Operand')], max_length=10)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('left_child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='left', to='engine.astnode')),
                ('right_child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='right', to='engine.astnode')),
            ],
        ),
    ]
