# Generated by Django 5.0 on 2024-10-17 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('department', models.CharField(max_length=50)),
                ('salary', models.FloatField()),
                ('experience', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='astnode',
            name='left_child',
        ),
        migrations.RemoveField(
            model_name='astnode',
            name='right_child',
        ),
        migrations.AddField(
            model_name='astnode',
            name='left',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_node', to='engine.astnode'),
        ),
        migrations.AddField(
            model_name='astnode',
            name='operator',
            field=models.CharField(blank=True, choices=[('AND', 'AND'), ('OR', 'OR')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='astnode',
            name='right',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_node', to='engine.astnode'),
        ),
        migrations.AlterField(
            model_name='astnode',
            name='node_type',
            field=models.CharField(choices=[('operator', 'Operator'), ('operand', 'Operand')], max_length=20),
        ),
    ]
