# Generated by Django 5.0 on 2024-10-17 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_users_remove_astnode_left_child_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.RemoveField(
            model_name='astnode',
            name='left',
        ),
        migrations.RemoveField(
            model_name='astnode',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='astnode',
            name='right',
        ),
        migrations.AddField(
            model_name='astnode',
            name='left_child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='left', to='engine.astnode'),
        ),
        migrations.AddField(
            model_name='astnode',
            name='right_child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='right', to='engine.astnode'),
        ),
        migrations.AlterField(
            model_name='astnode',
            name='node_type',
            field=models.CharField(choices=[('operator', 'Operator'), ('operand', 'Operand')], max_length=10),
        ),
    ]
