# Generated by Django 5.0 on 2024-10-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_delete_users_remove_astnode_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='astnode',
            name='is_root',
            field=models.BooleanField(default=False),
        ),
    ]
